<?php

namespace app\modules\api\v1\controllers;

use app\models\BlocoAula;

use yii\rest\ActiveController;
use Yii;
use yii\filters\auth\HttpBearerAuth;
use yii\httpclient\Client;


class BlocoAulaController extends ActiveController
{


    public function behaviors()
    {
        $behaviours = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviours['authenticator']['authMethods'] = [
            HttpBearerAuth::class
        ];

        return $behaviours;
    }
    public $modelClass = 'app\models\BlocoAula';





public function actionUpdateCorBloco($id_bloco, $cor) {

    $modelBlocoAula = BlocoAula::find()->where(['id_bloco' => $id_bloco])->one();
    $modelBlocoAula->cor = $cor;
   if( $modelBlocoAula->save()) {
       return true;
   } return false;

}

    public function actionUpdateVisibilidade($id_bloco, $visibility) {

        $modelBlocoAula = BlocoAula::find()->where(['id_bloco' => $id_bloco])->one();
        $modelBlocoAula->visivel = $visibility;
        if( $modelBlocoAula->save()) {
            return true;
        } return false;





    }

}