<?php

namespace app\modules\api\v1\controllers;

use app\modules\api\v1\resources\UserResource;
use app\modules\methods\getStringBetween;
use app\widgets\Alert;
use Yii;
use yii\filters\auth\HttpBearerAuth;
use yii\httpclient\Client;
use yii\rest\ActiveController;
use yii\web\Controller;


/**
 * Default controller for the `api-v1` module
 */
class DisciplinaController extends ActiveController
{
    public $modelClass = 'app\models\Disciplina';

    public function behaviors()
    {
        $behaviours = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviours['authenticator']['authMethods'] = [
            HttpBearerAuth::class
        ];

        return $behaviours;
    }

    public function actionCreateDisciplinas()
    {


        $user = UserResource::findOne(Yii::$app->user->identity);
        $userSessionId = $user->sessionId;


        $client = new Client(['baseUrl' => 'https://testing.estig.ipb.pt/sakai-ws/rest/',
            'responseConfig' => [
                'format' => Client::FORMAT_JSON
            ],]);
        $responseDisciplina = $client->get('sakai/getAllSitesForCurrentUser', ['sessionid' => $userSessionId])->setHeaders(['content-type' => 'application/json', 'authorization' => `Bearer $user->token`])->send();

        $xml = simplexml_load_string($responseDisciplina->content);


        $connection = \Yii::$app->db;

        foreach ($xml-> item as $item) {
            $connection->createCommand()->upsert('disciplina', [
                'codigo_disciplina' => $item->siteId,
                'nome' => $item->siteTitle,
            ])->execute();
             $connection->createCommand()->upsert('inscricao', [
                'numero_mecanografico_fk' => $user->numero_mecanografico,
                'codigo_disciplina' => $item->siteId,
                'ano_letivo' => getStringBetween::getStringAnoBetween($item->siteTitle, "(", "/"),
                'semestre' => getStringBetween::getStringSemestreBetween($item->siteTitle, "/", "."),
            ])->execute();


        }

        return "Sucesso";


    }


}
